# Generated by Django 5.2.7 on 2025-10-17 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tour', 'Tour'), ('hotel', 'Hotel'), ('car', 'Car Hire'), ('restaurant', 'Restaurant'), ('event', 'Event'), ('other', 'Other')], default='tour', max_length=50)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_hours', models.PositiveIntegerField(blank=True, help_text='Duration in hours', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_days', models.JSONField(blank=True, default=list, help_text='List of available weekdays')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
        ),
    ]
