# Generated by Django 5.2.7 on 2025-10-17 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="List of available weekdays (e.g. ['Monday', 'Tuesday'])"),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the tour in hours', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
