# Generated by Django 5.2.7 on 2025-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_date_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='bookings/proofs/'),
        ),
    ]
