# Generated by Django 5.2.7 on 2025-11-05 11:47

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('bookings', '0003_booking_proof_document'),
#     ]

#     operations = [
#     ]

# bookings/migrations/000X_fill_proof_document_placeholder.py
from django.db import migrations

def set_placeholder(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    placeholder = 'bookings/proofs/placeholder.pdf'   # path stored in DB (relative to MEDIA_ROOT)
    # update only rows with NULL or empty
    Booking.objects.filter(proof_document__isnull=True).update(proof_document=placeholder)
    Booking.objects.filter(proof_document='').update(proof_document=placeholder)

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_proof_document'),  # replace with the actual previous migration name
    ]

    operations = [
        migrations.RunPython(set_placeholder, reverse_code=migrations.RunPython.noop),
    ]